/* Ecowave Rental — content data + translations (NL default / FR / EN) */
window.ECOWAVE_DATA = {
    email: "Ecowave.bv@outlook.com",
  phone: "+32 466 29 75 11",
  whatsapp: "32466297511",
  company: {
    legalName: "Eco Wave BV",
    vat: "BE 1032.279.839",
    enterprise: "1032.279.839",
    street: "Gaston Fromontstraat 18",
    city: "2830 Willebroek",
    country: "België",
  },
  vehicle: {
    name: "Mercedes-Benz A-Class",
    trim: "AMG Line",
    category: { nl: "Premium hatchback", fr: "Compacte premium", en: "Premium hatchback" },
    pricePerDay: 110,
    priceWeekend: 350,
    priceWeek: 550,
    priceMonth: null,
    kmPerDay: 250,
    extraKm: 0.50,
    deposit1: 50,
    deposit2: 100,
    securityDeposit: 1000,
    year: 2017,
    specs: {
      power: { icon: "zap",       nl: "122 pk",     fr: "122 ch",     en: "122 hp" },
      fuel:  { icon: "fuel",      nl: "1.6 Benzine", fr: "1.6 Essence", en: "1.6 Petrol" },
      trans: { icon: "gauge",     nl: "Automaat",   fr: "Automatique", en: "Automatic" },
      seats: { icon: "users",     nl: "5 zitplaatsen", fr: "5 places", en: "5 seats" },
      doors: { icon: "door-open", nl: "5 deuren",   fr: "5 portes",   en: "5 doors" },
      year:  { icon: "calendar",  nl: "Bouwjaar 2017", fr: "Année 2017", en: "Year 2017" },
    },
    gallery: ["assets/car-front.png", "assets/car-rear.png", "assets/car-interior.png", "assets/car-dash.png"],
  },
  vehicleC: {
    id: "c-class",
    name: "Mercedes-Benz C-Class",
    trim: "AMG Line",
    category: { nl: "Premium berline", fr: "Berline premium", en: "Premium sedan" },
    pricePerDay: 160,
    priceWeekend: 500,
    priceWeek: null,
    priceMonth: null,
    kmPerDay: 200,
    extraKm: null,            // à préciser ultérieurement
    deposit1: 50,
    deposit2: 100,
    securityDeposit: 1000,
    year: 2023,
    tagline: {
      nl: "De nieuwe C 180 AMG Line — verfijnd, krachtig en volledig connected.",
      fr: "La nouvelle C 180 AMG Line — raffinée, puissante et entièrement connectée.",
      en: "The new C 180 AMG Line — refined, powerful and fully connected.",
    },
    specs: {
      power: { icon: "zap",       nl: "170 pk",        fr: "170 ch",       en: "170 hp" },
      fuel:  { icon: "fuel",      nl: "C 180 Benzine", fr: "C 180 Essence", en: "C 180 Petrol" },
      trans: { icon: "gauge",     nl: "9G-Tronic automaat", fr: "9G-Tronic auto", en: "9G-Tronic auto" },
      seats: { icon: "users",     nl: "5 zitplaatsen", fr: "5 places",     en: "5 seats" },
      doors: { icon: "door-open", nl: "4 deuren",      fr: "4 portes",     en: "4 doors" },
      year:  { icon: "calendar",  nl: "Bouwjaar 2023", fr: "Année 2023",   en: "Year 2023" },
    },
    gallery: [
      "assets/cclass-front.jpg", "assets/cclass-rear.jpg", "assets/cclass-side.jpg",
      "assets/cclass-wheel.jpg", "assets/cclass-screen.jpg", "assets/cclass-amg.jpg",
      "assets/cclass-detail.jpg", "assets/cclass-front2.jpg",
    ],
    highlights: {
      nl: ["AMG Line exterieur & interieur", "Volledig digitaal MBUX-display", "AMG veelspaaks lichtmetalen velgen", "Recent model — bouwjaar 2023", "Sport-onderstel & dynamische look", "Brandschoon afgeleverd, Ecowave-standaard"],
      fr: ["Extérieur & intérieur AMG Line", "Écran MBUX entièrement digital", "Jantes AMG multibranches", "Modèle récent — année 2023", "Châssis sport & look dynamique", "Livrée impeccable, standard Ecowave"],
      en: ["AMG Line exterior & interior", "Fully digital MBUX display", "AMG multi-spoke alloy wheels", "Recent model — year 2023", "Sport chassis & dynamic look", "Spotless on delivery, Ecowave standard"],
    },
    tech: [
      { icon: "zap",          label: { nl: "Vermogen", fr: "Puissance", en: "Power" },        val: { nl: "± 170 pk", fr: "± 170 ch", en: "± 170 hp" } },
      { icon: "fuel",         label: { nl: "Motor", fr: "Moteur", en: "Engine" },             val: { nl: "C 180 Benzine", fr: "C 180 Essence", en: "C 180 Petrol" } },
      { icon: "gauge",        label: { nl: "Transmissie", fr: "Transmission", en: "Transmission" }, val: { nl: "9G-Tronic automaat", fr: "9G-Tronic auto", en: "9G-Tronic auto" } },
      { icon: "users",        label: { nl: "Plaatsen", fr: "Places", en: "Seats" },           val: { nl: "5", fr: "5", en: "5" } },
      { icon: "door-open",    label: { nl: "Carrosserie", fr: "Carrosserie", en: "Body" },    val: { nl: "Berline · 4 deuren", fr: "Berline · 4 portes", en: "Sedan · 4 doors" } },
      { icon: "calendar",     label: { nl: "Bouwjaar", fr: "Année", en: "Year" },             val: { nl: "2023", fr: "2023", en: "2023" } },
    ],
  },
  reviews: [
    { initials: "SD", name: "Sophie De Vos", city: { nl: "Antwerpen", fr: "Anvers", en: "Antwerp" },
      text: { nl: "Vlekkeloze service. De auto was brandschoon en de afhandeling via WhatsApp ging supersnel.",
              fr: "Service impeccable. La voiture était immaculée et tout s'est réglé très vite via WhatsApp.",
              en: "Flawless service. The car was spotless and everything was handled super fast over WhatsApp." } },
    { initials: "LM", name: "Lucas Martin", city: { nl: "Brussel", fr: "Bruxelles", en: "Brussels" },
      text: { nl: "Transparante prijzen, geen verrassingen. Precies wat je verwacht van een premium verhuurder.",
              fr: "Prix transparents, aucune surprise. Exactement ce qu'on attend d'un loueur premium.",
              en: "Transparent pricing, no surprises. Exactly what you expect from a premium rental." } },
    { initials: "AK", name: "Amélie Klein", city: { nl: "Brussel", fr: "Bruxelles", en: "Brussels" },
      text: { nl: "Reserveren in twee minuten en de wagen stond klaar. Echt een professionele ervaring.",
              fr: "Réservation en deux minutes et la voiture était prête. Une expérience vraiment pro.",
              en: "Booked in two minutes and the car was ready. A genuinely professional experience." } },
  ],
};

window.ECOWAVE_I18N = {
  nl: {
    nav: { vehicle: "Wagen", booking: "Reserveren", conditions: "Voorwaarden", reviews: "Reviews" },
    hero: {
      eyebrow: "Brussel · Antwerpen · België",
      title: "Premium autoverhuur in Brussel & Antwerpen",
      lead: "Eenvoudig boeken. Transparante prijzen. Professionele service.",
      availability: "Beschikbaarheid", reserve: "Nu reserveren", whatsapp: "WhatsApp",
      stat1n: "24/7", stat1l: "Bereikbaar", stat2n: "5★", stat2l: "Beoordeling", stat3n: "0", stat3l: "Verborgen kosten",
      badge: "Vandaag beschikbaar",
    },
    trust: { t1: "Gratis annulering", t1s: "Tot 48u vooraf", t2: "Direct bevestigd", t2s: "Via WhatsApp", t3: "Volledig verzekerd", t3s: "Omnium inbegrepen", t4: "Geen verborgen kosten", t4s: "Transparante prijs" },
    vehicle: { eyebrow: "Onze wagen", title: "Maak kennis met de wagen", lead: "Eén zorgvuldig onderhouden premium wagen, klaar voor uw rit door België.", perday: "/ dag", deposit: "Waarborg", reserveBtn: "Reserveer deze wagen", from: "vanaf" },
    booking: { eyebrow: "Reserveren", title: "Kies uw data", lead: "Selecteer ophaal- en retourdatum. Uw selectie vult automatisch het formulier in.", name: "Volledige naam", phone: "Telefoon", email: "E-mail", pickup: "Ophaaldatum", ret: "Retourdatum", notes: "Opmerkingen (optioneel)", notesPh: "Vlucht, ophaaltijd, extra wensen…", submit: "Bevestig via WhatsApp", note: "Geen vooruitbetaling online. U bevestigt de reservatie via WhatsApp en betaalt de waarborg bij ophaling.", success: "Bedankt! We openen WhatsApp om uw reservatie te bevestigen.", selectDates: "Kies eerst uw data", errName: "Vul uw naam in", errPhone: "Vul een geldig telefoonnummer in", errEmail: "Vul een geldig e-mailadres in", errDates: "Selecteer ophaal- en retourdatum" },
    cal: { legendSel: "Selectie", legendRange: "Inbegrepen nachten", legendFree: "Beschikbaar", legendBooked: "Geboekt" },
    conditions: { eyebrow: "Voorwaarden", title: "Heldere huurvoorwaarden", lead: "Alles vooraf duidelijk. Geen kleine lettertjes.",
      items: [
        { icon: "user-check", t: "Min. leeftijd 20 jaar", d: "Bestuurder is minstens 20 jaar bij ophaling." },
        { icon: "id-card", t: "Rijbewijs 1 jaar", d: "Minimaal 1 jaar geldig rijbewijs vereist." },
        { icon: "route", t: "250 km/dag inbegrepen", d: "Extra kilometers aan een vast tarief van €0,50/km." },
        { icon: "wallet", t: "Waarborg €1.000", d: "Volledig terugbetaald na controle van de wagen." },
        { icon: "banknote", t: "Reservatie & betaling", d: "€50 (1 dag) of €100 (2+ dagen). Cash of overschrijving." },
        { icon: "shield-check", t: "Volledig verzekerd", d: "Omnium en bijstand inbegrepen." },
      ] },
    reviews: { eyebrow: "Reviews", title: "Wat klanten zeggen", lead: "Beoordeeld met 5 sterren door bestuurders in Brussel en Antwerpen." },
    footer: { tagline: "Premium autoverhuur in Brussel & Antwerpen. Eenvoudig, transparant, professioneel.", explore: "Ontdek", contact: "Contact", legal: "Juridisch", terms: "Algemene voorwaarden", privacy: "Privacybeleid", legalNotice: "Wettelijke vermeldingen", booknow: "Reserveer nu", rights: "Alle rechten voorbehouden." },
    chat: { title: "Ecowave Assistent", status: "Online · AI-assistent", ph: "Stel een vraag…", greeting: "Hallo! 👋 Ik help u graag met beschikbaarheid, prijzen en voorwaarden. Waarmee kan ik u helpen?", c1: "Beschikbaarheid", c2: "Prijs per dag", c3: "Voorwaarden", powered: "AI-assistent · antwoorden ter info" },
  },
  fr: {
    nav: { vehicle: "Véhicule", booking: "Réserver", conditions: "Conditions", reviews: "Avis" },
    hero: {
      eyebrow: "Bruxelles · Anvers · Belgique",
      title: "Location de voiture premium à Bruxelles & Anvers",
      lead: "Réservation simple. Prix transparents. Service professionnel.",
      availability: "Disponibilité", reserve: "Réserver", whatsapp: "WhatsApp",
      stat1n: "24/7", stat1l: "Joignable", stat2n: "5★", stat2l: "Note", stat3n: "0", stat3l: "Frais cachés",
      badge: "Disponible aujourd'hui",
    },
    trust: { t1: "Annulation gratuite", t1s: "Jusqu'à 48h avant", t2: "Confirmation directe", t2s: "Via WhatsApp", t3: "Entièrement assuré", t3s: "Omnium inclus", t4: "Aucun frais caché", t4s: "Prix transparent" },
    vehicle: { eyebrow: "Notre véhicule", title: "Découvrez le véhicule", lead: "Un véhicule premium soigneusement entretenu, prêt pour vos trajets en Belgique.", perday: "/ jour", deposit: "Caution", reserveBtn: "Réserver ce véhicule", from: "à partir de" },
    booking: { eyebrow: "Réserver", title: "Choisissez vos dates", lead: "Sélectionnez la prise et le retour. Votre sélection remplit le formulaire.", name: "Nom complet", phone: "Téléphone", email: "E-mail", pickup: "Date de prise", ret: "Date de retour", notes: "Remarques (facultatif)", notesPh: "Vol, heure de prise, demandes…", submit: "Confirmer via WhatsApp", note: "Aucun paiement en ligne. Vous confirmez via WhatsApp et payez la caution au retrait.", success: "Merci ! Nous ouvrons WhatsApp pour confirmer votre réservation.", selectDates: "Choisissez d'abord vos dates", errName: "Indiquez votre nom", errPhone: "Numéro de téléphone invalide", errEmail: "Adresse e-mail invalide", errDates: "Sélectionnez les dates de prise et de retour" },
    cal: { legendSel: "Sélection", legendRange: "Nuits incluses", legendFree: "Disponible", legendBooked: "Réservé" },
    conditions: { eyebrow: "Conditions", title: "Conditions claires", lead: "Tout est clair d'avance. Pas de petits caractères.",
      items: [
        { icon: "user-check", t: "Âge min. 20 ans", d: "Le conducteur a au moins 20 ans à la prise." },
        { icon: "id-card", t: "Permis depuis 1 an", d: "Permis valide depuis au moins 1 an." },
        { icon: "route", t: "250 km/jour inclus", d: "Kilomètres supplémentaires à 0,50 €/km." },
        { icon: "wallet", t: "Caution 1 000 €", d: "Intégralement remboursée après contrôle du véhicule." },
        { icon: "banknote", t: "Réservation & paiement", d: "50 € (1 jour) ou 100 € (2+ jours). Espèces ou virement." },
        { icon: "shield-check", t: "Entièrement assuré", d: "Omnium et assistance inclus." },
      ] },
    reviews: { eyebrow: "Avis", title: "Ce que disent nos clients", lead: "Noté 5 étoiles par les conducteurs à Bruxelles et Anvers." },
    footer: { tagline: "Location premium à Bruxelles & Anvers. Simple, transparent, professionnel.", explore: "Explorer", contact: "Contact", legal: "Légal", terms: "Conditions générales", privacy: "Politique de confidentialité", legalNotice: "Mentions légales", booknow: "Réserver", rights: "Tous droits réservés." },
    chat: { title: "Assistant Ecowave", status: "En ligne · Assistant IA", ph: "Posez une question…", greeting: "Bonjour ! 👋 Je vous aide avec la disponibilité, les prix et les conditions. Comment puis-je aider ?", c1: "Disponibilité", c2: "Prix par jour", c3: "Conditions", powered: "Assistant IA · réponses à titre indicatif" },
  },
  en: {
    nav: { vehicle: "Vehicle", booking: "Booking", conditions: "Conditions", reviews: "Reviews" },
    hero: {
      eyebrow: "Brussels · Antwerp · Belgium",
      title: "Premium car rental in Brussels & Antwerp",
      lead: "Simple booking. Transparent pricing. Professional service.",
      availability: "Check availability", reserve: "Reserve now", whatsapp: "WhatsApp",
      stat1n: "24/7", stat1l: "Reachable", stat2n: "5★", stat2l: "Rating", stat3n: "0", stat3l: "Hidden fees",
      badge: "Available today",
    },
    trust: { t1: "Free cancellation", t1s: "Up to 48h before", t2: "Instant confirmation", t2s: "Via WhatsApp", t3: "Fully insured", t3s: "Comprehensive incl.", t4: "No hidden fees", t4s: "Transparent price" },
    vehicle: { eyebrow: "Our vehicle", title: "Meet the vehicle", lead: "One carefully maintained premium vehicle, ready for your drive across Belgium.", perday: "/ day", deposit: "Deposit", reserveBtn: "Reserve this vehicle", from: "from" },
    booking: { eyebrow: "Booking", title: "Choose your dates", lead: "Pick your pickup and return dates. Your selection auto-fills the form.", name: "Full name", phone: "Phone", email: "Email", pickup: "Pickup date", ret: "Return date", notes: "Notes (optional)", notesPh: "Flight, pickup time, extra requests…", submit: "Confirm via WhatsApp", note: "No online prepayment. You confirm via WhatsApp and pay the deposit at pickup.", success: "Thank you! Opening WhatsApp to confirm your reservation.", selectDates: "Select your dates first", errName: "Enter your name", errPhone: "Enter a valid phone number", errEmail: "Enter a valid email address", errDates: "Select pickup and return dates" },
    cal: { legendSel: "Selection", legendRange: "Nights included", legendFree: "Available", legendBooked: "Booked" },
    conditions: { eyebrow: "Conditions", title: "Clear rental conditions", lead: "Everything clear upfront. No fine print.",
      items: [
        { icon: "user-check", t: "Min. age 20", d: "Driver must be at least 20 at pickup." },
        { icon: "id-card", t: "Licence held 1 year", d: "Valid driving licence for at least 1 year." },
        { icon: "route", t: "250 km/day included", d: "Extra distance at a flat €0.50/km." },
        { icon: "wallet", t: "Deposit €1,000", d: "Fully refunded after the car is checked." },
        { icon: "banknote", t: "Reservation & payment", d: "€50 (1 day) or €100 (2+ days). Cash or bank transfer." },
        { icon: "shield-check", t: "Fully insured", d: "Comprehensive cover & assistance." },
      ] },
    reviews: { eyebrow: "Reviews", title: "What customers say", lead: "Rated 5 stars by drivers in Brussels and Antwerp." },
    footer: { tagline: "Premium car rental in Brussels & Antwerp. Simple, transparent, professional.", explore: "Explore", contact: "Contact", legal: "Legal", terms: "Terms & conditions", privacy: "Privacy policy", legalNotice: "Legal notice", booknow: "Book now", rights: "All rights reserved." },
    chat: { title: "Ecowave Assistant", status: "Online · AI assistant", ph: "Ask a question…", greeting: "Hello! 👋 I can help with availability, pricing and conditions. What would you like to know?", c1: "Availability", c2: "Price per day", c3: "Conditions", powered: "AI assistant · answers for guidance" },
  },
};

/* Vehicle registry — resolve any vehicle by id (scalable: add a car here + in D.fleet) */
window.ECOWAVE_DATA.vehiclesById = {
  "a-class": window.ECOWAVE_DATA.vehicle,
  "c-class": window.ECOWAVE_DATA.vehicleC,
};
window.ECOWAVE_DATA.getVehicle = function (id) {
  return window.ECOWAVE_DATA.vehiclesById[id] || window.ECOWAVE_DATA.vehicle;
};
